
services:
  reverse-proxy.asistify.local:
    container_name: reverse-proxy.asistify.local
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - asistify_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - asistify_network

networks:
  asistify_network:
    external: true