
services:
  reverse-proxy.asistify.local:
    container_name: reverse-proxy.asistify.local
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: unless-stopped
    ports:
      - "80:8090"
    networks:
      - asistify_network

networks:
  asistify_network:
    external: true